"""Figures for Chapter 5 (supervised fine-tuning). Writes results/figs_ch5.json (key -> svg).
Colours come only from CSS classes, so every figure follows the site's themes. Every number is read from a results/ch5_*.json
file written by a script (ch5_data.py, ch5_template.py, ch5_lora_math.py, ch5_sft.py, ch5_reference.py)."""
import json, math, os, textwrap
from figlib import svg, text, box, arrow, esc
from agentfig import line, hbars
from alammar import frame, brace, matrix, vec
from figs_ch4 import para, block, chart

J = lambda n: json.load(open(f'results/{n}.json')) if os.path.exists(f'results/{n}.json') else None
LM, TPL, LORA, FULL, REF, DATA = J('ch5_lora_math'), J('ch5_template'), J('ch5_sft_lora'), J('ch5_sft_full'), J('ch5_reference'), J('ch5_data')
PLAIN, SPEC = J('ch5_sft_lora_plain'), J('ch5_special_tokens')
F = {}


# ---------------------------------------------------------------- 1. pretraining vs SFT
def vs_pretrain():
    b = [text(200, 24, 'Pretraining', 't-title', 'middle'), text(580, 24, 'Supervised fine-tuning', 't-title', 'middle'), line(390, 10, 390, 300, 'edge-dim')]
    rows = [('data', 'trillions of tokens of web, books, code', 'thousands of chosen conversations'),
            ('format', 'one long stream of documents', 'chat template with turn tokens'),
            ('learned tokens', 'every token', 'only the assistant reply + <|im_end|>'),
            ('loss', 'next-token cross-entropy', 'the same next-token cross-entropy'),
            ('compute', '6ND with D ~ 1e13 tokens', 'D ~ 1e5 to 1e9 tokens'),
            ('result', 'knows things, continues text', 'answers, in format, then stops')]
    y = 46
    for k, a, c in rows:
        same = k == 'loss'
        b += [box(20, y, 360, 36, 'box-1' if not same else 'box-3', 8), text(30, y + 23, f'{k}:', 't-muted'), text(140, y + 23, a, 't-tick')]
        b += [box(400, y, 360, 36, 'box-2' if not same else 'box-3', 8), text(410, y + 23, f'{k}:', 't-muted'), text(520, y + 23, c, 't-tick')]
        y += 44
    b.append(text(390, y + 14, 'Green: the one thing that does not change.', 't-muted', 'middle'))
    return svg(780, y + 26, 'A side-by-side comparison of pretraining and supervised fine-tuning: data, format, learned tokens, loss, compute and result.', b)


F['ch5_vs_pretrain'] = vs_pretrain()


# ---------------------------------------------------------------- 2. timeline of instruction datasets
def timeline():
    items = [('2021', 'FLAN', 'over 60 NLP datasets, 10 templates each', 1), ('2021', 'T0 / P3', 'crowd-sourced prompts for many datasets', 1),
             ('2022', 'Super-NaturalInstructions', '1,616 tasks with expert-written definitions', 1),
             ('2022', 'InstructGPT SFT', 'about 13k demonstrations written by labelers', 3),
             ('2022', 'Flan-T5 / Flan-PaLM', '1.8K tasks plus chain-of-thought examples', 1),
             ('2022', 'Self-Instruct', '52K instructions generated by GPT-3 from 175 seeds', 2),
             ('2023', 'Alpaca', '52K generated by text-davinci-003 for under 500 dollars', 2),
             ('2023', 'LIMA', '1,000 examples chosen and written by hand', 3),
             ('2023', 'Tulu 2', '326K examples mixed from many sources', 1),
             ('2024', 'Tulu 3', '939K examples, mostly synthetic, built skill by skill', 2)]
    cls = {1: 'box-1', 2: 'box-2', 3: 'box-3'}
    b = [text(20, 24, 'Where instruction data came from, 2021 to 2024', 't-title')]
    y = 40
    for yr, name, d, k in items:
        b += [text(56, y + 17, yr, 't-tick', 'end'), f'<circle class="node on" cx="76" cy="{y + 12}" r="5"/>',
              box(92, y, 210, 24, cls[k], 6), text(102, y + 16.5, name, 't-tick t-strong'), text(316, y + 16.5, d, 't-tick')]
        y += 30
    b.append(line(76, 46, 76, y - 18, 'edge-dim'))
    b += [f'<rect class="box-1" x="92" y="{y + 4}" width="12" height="12" rx="2"/>', text(110, y + 14, 'reformatted NLP datasets or mixtures', 't-tick'),
          f'<rect class="box-2" x="370" y="{y + 4}" width="12" height="12" rx="2"/>', text(388, y + 14, 'model-generated', 't-tick'),
          f'<rect class="box-3" x="520" y="{y + 4}" width="12" height="12" rx="2"/>', text(538, y + 14, 'written or chosen by people', 't-tick')]
    return svg(780, y + 28, 'A timeline of instruction datasets from FLAN in 2021 to Tulu 3 in 2024.', b)


F['ch5_timeline'] = timeline()


# ---------------------------------------------------------------- 3. multi-turn masking
def multiturn():
    if not TPL:
        return None
    pieces, learned = TPL['multi']['pieces'], TPL['multi']['learned']
    b = [text(20, 24, 'A two-turn chat: which tokens does SFT learn from? (ch5_template.py)', 't-title')]
    x, y = 20, 44
    for p, l in zip(pieces, learned):
        s = p.replace('\n', '↵')
        w = max(20, 7.0 * len(s) + 10)
        if x + w > 770:
            x, y = 20, y + 34
        b += [box(x, y, w, 26, 'box-3' if l else ('box-on' if s.startswith('<|') else 'box'), 5), text(x + w / 2, y + 17.5, s, 't-tick', 'middle')]
        x += w + 4
    y += 50
    n = sum(learned)
    b += [f'<rect class="box-3" x="20" y="{y - 10}" width="14" height="14" rx="3"/>', text(40, y + 1, f'learned: {n} of {len(pieces)} tokens (the two replies and their <|im_end|>)', 't-tick'),
          f'<rect class="box-on" x="20" y="{y + 10}" width="14" height="14" rx="3"/>', text(40, y + 21, 'special tokens (masked unless they close a reply)', 't-tick'),
          f'<rect class="box" x="20" y="{y + 30}" width="14" height="14" rx="3"/>', text(40, y + 41, 'ordinary masked tokens: system prompt, user turns, assistant headers', 't-tick')]
    return svg(790, y + 56, 'A two-turn conversation token by token, with the learned tokens highlighted.', b)


F['ch5_multiturn'] = multiturn()


# ---------------------------------------------------------------- 4. per-token losses before and after
def pertoken():
    if not TPL or 'lora' not in TPL:
        return None
    runs = [('base model', TPL['base'], 's1'), ('plain LoRA', TPL['lora_plain'], 's2'), ('LoRA + 2 token rows', TPL['lora'], 's3')]
    base = TPL['base']['rows']
    b = [text(20, 24, 'Loss at every learned token of one example, before and after fine-tuning (ch5_template.py)', 't-title')]
    n = len(base)
    cw = 700 / n
    top, H = 56, 200
    vmax = 15
    Y = lambda v: top + H - min(v, vmax) / vmax * H
    for t in range(0, vmax + 1, 5):
        b += [f'<line class="grid" x1="60" y1="{Y(t):.1f}" x2="770" y2="{Y(t):.1f}"/>', text(52, Y(t) + 4, str(t), 't-tick', 'end')]
    bw = cw * 0.27
    for i in range(n):
        x = 66 + i * cw
        for k, (name, R, cls) in enumerate(runs):
            p, v = R['rows'][i]
            b.append(f'<g class="mark"><title>{esc(p)}: {name} {v:.3f}</title><rect class="{cls}" x="{x + k * (bw + 1):.1f}" y="{Y(v):.1f}" width="{bw:.1f}" height="{max(0.8, top + H - Y(v)):.1f}" rx="2"/></g>')
        lab = base[i][0].replace('\n', '\u21b5').strip() or '\u2423'
        cx = x + cw * 0.45
        b.append(text(cx, top + H + 12, lab, 't-tick', 'end', f' transform="rotate(-45 {cx:.1f} {top + H + 12})"'))
    last = 66 + (n - 1) * cw
    for k, (name, R, cls) in enumerate(runs):
        v = R['rows'][-1][1]
        b.append(text(last + k * (bw + 1) + bw / 2, Y(v) - 5, f'{v:.2f}' if v > 0.1 else f'{v:.3f}', 't-tick', 'middle'))
    b.append(text(60, top - 14, 'loss in nats (-log p of the true token)', 't-muted'))
    yy = top + H + 96
    for k, (name, R, cls) in enumerate(runs):
        b += [f'<rect class="{cls}" x="60" y="{yy - 10 + 20 * k}" width="10" height="10" rx="2"/>',
              text(76, yy + 20 * k, f'{name}: mean over the 12 tokens {R["masked"]:.3f}, without <|im_end|> {R["no_end"]:.3f}', 't-tick')]
    return svg(790, yy + 66, 'Bar chart of the loss at each learned token of one example for the base model, plain LoRA and LoRA with the two token rows trained.', b)


F['ch5_pertoken'] = pertoken()


# ---------------------------------------------------------------- 5. padding vs packing
def packing():
    if not TPL or 'bucket_slots' not in TPL['pack']:
        return None
    P = TPL['pack']
    b = [text(20, 24, f'Padding or packing the {P["real"]:,} real tokens of our 1,000 training examples (ch5_template.py)', 't-title')]
    W = 560
    mx = max(P['pad_slots'], P['bucket_slots'])
    bars = [('random batches of 8, padded to the longest', P['pad_slots'], 's2'),
            ('the same, rounded up to a multiple of 128 (our run)', P['bucket_slots'], 's4'),
            ('packed into full rows of 384', P['packed_slots'], 's3')]
    for i, (name, slots, cls) in enumerate(bars):
        y = 56 + i * 58
        full = W * slots / mx
        real = W * P['real'] / mx
        b += [text(20, y - 8, f'{name}: {slots:,} slots, {1 - P["real"] / slots:.0%} padding', 't-tick')]
        b += [f'<rect class="{cls}" x="20" y="{y}" width="{real:.1f}" height="24" rx="3"/>', box(20 + real, y, max(0.5, full - real), 24, 'box-ghost', 3)]
    b += para(20, 56 + 3 * 58 + 6, ['Filled: real tokens. Dashed: padding, which costs compute and teaches nothing.',
                                    'Packing puts several examples in one row; the attention or at least the loss must then be kept per example.'], 't-muted')
    return svg(760, 56 + 3 * 58 + 44, 'Three bars comparing token slots used by padded batches, padded batches rounded to 128, and packing.', b)


F['ch5_packing'] = packing()


# ---------------------------------------------------------------- 6. the LoRA picture with real shapes
def lora_picture():
    b = [text(20, 24, 'LoRA on one weight matrix of Qwen2.5-0.5B (q_proj, 896 x 896), rank r = 16', 't-title')]
    b += [box(40, 60, 170, 170, 'box-1', 6), text(125, 140, 'W (frozen)', 't-note', 'middle'), text(125, 160, '896 x 896', 't-tick', 'middle'),
          text(125, 178, '802,816 numbers', 't-muted', 'middle')]
    b.append(text(240, 150, '+', 't-big', 'middle'))
    b += [box(270, 60, 24, 170, 'box-2', 4), text(282, 250, 'B', 't-math', 'middle'), text(282, 268, '896 x 16', 't-tick', 'middle')]
    b += [box(305, 60, 170, 24, 'box-2', 4), text(390, 104, 'A', 't-math', 'middle'), text(390, 122, '16 x 896', 't-tick', 'middle')]
    b.append(text(390, 160, 'B starts at 0, A random:', 't-muted', 'middle'))
    b.append(text(390, 177, 'the model starts unchanged', 't-muted', 'middle'))
    b += para(500, 76, ['h = W x + (alpha / r) B A x', '', 'trained: A and B only', f'16 x (896 + 896) = 28,672 numbers',
                        f'= 3.6% of this matrix', '', 'the update B A has rank at most 16', 'merge after training:',
                        'W\' = W + (alpha / r) B A, no extra cost'], 't-tick')
    return svg(780, 285, 'The LoRA reparametrization on the q_proj matrix: a frozen 896 by 896 weight plus the product of a 896 by 16 matrix B and a 16 by 896 matrix A.', b)


F['ch5_lora'] = lora_picture()


# ---------------------------------------------------------------- 7. a rank-1 update on a 4x4 matrix
def rank1():
    T = LM['toy']
    b = [text(20, 24, 'A rank-1 update: 8 trained numbers make a 4 x 4 change (ch5_lora_math.py)', 't-title')]
    cell = 44
    def grid(x0, y0, M, title):
        g = [text(x0 + len(M[0]) * cell / 2, y0 - 10, title, 't-note', 'middle')]
        mx = max(abs(v) for r in M for v in r) or 1
        for i, r in enumerate(M):
            for j, v in enumerate(r):
                cls = 's1' if v >= 0 else 's2'
                g.append(f'<rect class="{cls}" x="{x0 + j * cell + 1}" y="{y0 + i * cell + 1}" width="{cell - 2}" height="{cell - 2}" rx="3" style="fill-opacity:{0.15 + 0.6 * abs(v) / mx:.2f}"/>')
                g.append(text(x0 + j * cell + cell / 2, y0 + i * cell + cell / 2 + 4, f'{v:.2f}', 't-cell', 'middle'))
        return g
    b += grid(40, 70, [[v] for v in T['B']], 'B (4 x 1)')
    b.append(text(110, 160, 'x', 't-big', 'middle'))
    b += grid(130, 136, [T['A']], 'A (1 x 4)')
    b.append(text(330, 160, '=', 't-big', 'middle'))
    b += grid(360, 70, T['dW'], 'Delta W = B A (4 x 4)')
    b += para(560, 90, ['Every row of Delta W is a multiple', 'of the same row A; every column', 'is a multiple of the same column B.',
                        '', '16 numbers, 8 parameters, rank 1.', 'At rank r: r x (d_in + d_out)', 'parameters instead of d_in x d_out.'], 't-tick')
    return svg(800, 270, 'A worked rank-1 update: a column B times a row A gives a 4 by 4 matrix whose rows are all multiples of A.', b)


F['ch5_rank1'] = rank1()


# ---------------------------------------------------------------- 8. trainable parameters by rank
def ranks():
    rows = LM['ranks']
    b = [text(20, 24, f'Trainable parameters for LoRA on all 7 linear layers of Qwen2.5-0.5B ({LM["total"]:,} parameters in all)', 't-title')]
    lo, hi = 5, 9
    X = lambda v: 140 + (math.log10(v) - lo) / (hi - lo) * 520
    for e in range(lo, hi + 1):
        b += [f'<line class="grid" x1="{X(10 ** e):.1f}" y1="40" x2="{X(10 ** e):.1f}" y2="{46 + 28 * (len(rows) + 1)}"/>', text(X(10 ** e), 60 + 28 * (len(rows) + 1), f'1e{e}', 't-tick', 'middle')]
    for i, (r, n, f) in enumerate(rows):
        y = 48 + i * 28
        b.append(text(130, y + 15, f'rank {r}', 't-tick', 'end'))
        b.append(f'<g class="mark"><title>rank {r}: {n:,}</title><rect class="{"s3" if r == 16 else "s1"}" x="140" y="{y + 3}" width="{X(n) - 140:.1f}" height="17" rx="3"/></g>')
        b.append(text(X(n) + 6, y + 16, f'{n:,} ({f:.2%})', 't-val'))
    y = 48 + len(rows) * 28
    b.append(text(130, y + 15, 'full model', 't-tick', 'end'))
    b.append(f'<rect class="s2" x="140" y="{y + 3}" width="{X(LM["total"]) - 140:.1f}" height="17" rx="3"/>')
    b.append(text(X(LM['total']) + 6, y + 16, f'{LM["total"]:,}', 't-val'))
    return svg(780, 96 + 28 * (len(rows) + 1), 'Trainable parameter counts for LoRA ranks from 1 to 256 compared with the full model, on a log scale.', b)


F['ch5_ranks'] = ranks()


# ---------------------------------------------------------------- 9. memory: full vs LoRA vs QLoRA
def memory():
    rows = LM['mem']
    b = [text(20, 24, 'Training state for Qwen2.5-0.5B: weights + gradients + AdamW (before activations)', 't-title')]
    mx = rows[0][1]
    for i, (name, by) in enumerate(rows):
        y = 50 + i * 40
        w = 420 * by / mx
        b.append(text(300, y + 18, name, 't-tick', 'end'))
        b.append(f'<rect class="{["s2", "s1", "s3"][i]}" x="310" y="{y + 4}" width="{w:.1f}" height="22" rx="3"/>')
        b.append(text(318 + w, y + 20, f'{by / 2**30:.2f} GiB', 't-val'))
    b += para(20, 186, ['Full fine-tuning keeps 16 bytes per parameter (Chapter 4). LoRA keeps the frozen weights in 16 bits (2 bytes)',
                        'and full training state only for its 8.8M adapter parameters. QLoRA stores the frozen weights in 4 bits.',
                        f'For a 65B model the frozen weights alone are {LM["w_65B"][0]:.0f} GiB in bf16 and {LM["w_65B"][1]:.0f} GiB in 4-bit, which is why QLoRA fits it on one 48 GB GPU.'], 't-muted')
    return svg(780, 240, 'Bars of training memory for full fine-tuning, LoRA and QLoRA of Qwen2.5-0.5B.', b)


F['ch5_memory'] = memory()


# ---------------------------------------------------------------- 10. the SFT loss curves
def loss_curve():
    if not LORA:
        return None
    ser = [('train loss', LORA['step'], LORA['loss'], 'l1', 's1'), ('held-out: LoRA + rows', LORA['val_step'], LORA['val'], 'l3', 's3')]
    if PLAIN:
        ser.append(('held-out: plain LoRA', PLAIN['val_step'], PLAIN['val'], 'l2', 's2'))
    if FULL:
        ser.append(('held-out: full FT', FULL['val_step'], FULL['val'], 'l4', 's4'))
    S = LORA['step'][-1]
    lo = min(min(LORA['loss']), min(LORA['val'])) - 0.1
    hi = max(max(LORA['loss']), max(LORA['val'])) + 0.1
    lo, hi = math.floor(lo * 10) / 10, math.ceil(hi * 10) / 10
    ticks = [round(lo + k * 0.2, 1) for k in range(int((hi - lo) / 0.2) + 1)]
    b, X, Y = chart(80, 64, 520, 230, ser, (0, S), (lo, hi), [0, S // 4, S // 2, 3 * S // 4, S], ticks, fx=lambda v: f'{int(v)}',
                    fy=lambda v: f'{v:.1f}', xlabel='training step (8 examples per step)', ylabel='loss per reply token (nats)')
    b = [p for p in b if not ('circle class="s1' in p)]
    b.insert(0, text(20, 24, 'SFT of Qwen2.5-0.5B on 1,000 Alpaca examples: loss per reply token', 't-title'))
    if REF:
        ins = REF['Qwen/Qwen2.5-0.5B-Instruct']['heldout']
        b.append(f'<line class="base-line" x1="80" y1="{Y(ins):.1f}" x2="600" y2="{Y(ins):.1f}"/>')
        b.append(text(80, 362, f'dashed line: Qwen2.5-0.5B-Instruct on the same held-out examples, {ins:.3f}', 't-muted'))
    return svg(800, 372, 'Training loss and held-out loss over the fine-tuning steps.', b)


F['ch5_loss'] = loss_curve()


# ---------------------------------------------------------------- 11. checks grid
def checks():
    if not (LORA and REF):
        return None
    cols = [('base', REF['Qwen/Qwen2.5-0.5B']['checks'])] + ([('plain LoRA', PLAIN['checks'])] if PLAIN else []) + [('LoRA + rows', LORA['checks'])]
    if FULL:
        cols.append(('full SFT', FULL['checks']))
    cols.append(('Qwen Instruct', REF['Qwen/Qwen2.5-0.5B-Instruct']['checks']))
    short = ['3 bullet points', 'one word', "'HELLO' only", 'lowercase, 1 sentence', 'just the number 42', "'bonjour' only",
             'haiku, 3 lines', 'JSON name + age', 'Tokyo, 1 sentence', 'exactly 2 sentences', 'under 30 words', "starts with 'Yes'"]
    b = [text(20, 24, 'Twelve instruction-following checks (pass = ended its turn and met the constraint)', 't-title')]
    x0, y0, cw, rh = 170, 70, 120, 24
    for j, (name, rows) in enumerate(cols):
        b.append(text(x0 + j * cw + cw / 2, y0 - 12, name, 't-tick t-strong', 'middle'))
    for i, s in enumerate(short):
        y = y0 + i * rh
        b.append(text(x0 - 10, y + 16, s, 't-tick', 'end'))
        for j, (name, rows) in enumerate(cols):
            r = rows[i]
            cls = 'box-3' if r['passed'] else ('box-2' if not r['stopped'] else 'box')
            lab = 'pass' if r['passed'] else ('runs on' if not r['stopped'] else 'fail')
            b += [box(x0 + j * cw + 6, y + 2, cw - 12, rh - 4, cls, 4), text(x0 + j * cw + cw / 2, y + 16, lab, 't-tick', 'middle')]
    y = y0 + len(short) * rh
    b.append(text(x0 - 10, y + 18, 'passed', 't-tick t-strong', 'end'))
    for j, (name, rows) in enumerate(cols):
        b.append(text(x0 + j * cw + cw / 2, y + 18, f'{sum(r["passed"] for r in rows)} / {len(rows)}', 't-val', 'middle'))
    b.append(text(20, y + 44, '"runs on": did not end its turn within 150 tokens. "fail": ended its turn but broke the constraint.', 't-muted'))
    return svg(780, y + 56, 'A grid of pass and fail results on twelve instruction-following checks for the base model, our fine-tuned models and Qwen Instruct.', b)


F['ch5_checks'] = checks()


# ---------------------------------------------------------------- 12. forgetting
def forgetting():
    if not (LORA and REF):
        return None
    models = [('base', REF['Qwen/Qwen2.5-0.5B'])] + ([('plain LoRA', PLAIN)] if PLAIN else []) + [('LoRA + rows', LORA)]
    if FULL:
        models.append(('full SFT', FULL))
    models.append(('Qwen Instruct', REF['Qwen/Qwen2.5-0.5B-Instruct']))
    b = [text(20, 24, 'What did fine-tuning cost? Two probes of what the base model could already do', 't-title')]
    b.append(text(20, 50, 'perplexity on Wikipedia text (wikitext-2, lower is better)', 't-note'))
    mx = max(m['wikitext_ppl'] for _, m in models)
    for i, (n, m) in enumerate(models):
        y = 60 + i * 26
        w = 300 * m['wikitext_ppl'] / mx
        b += [text(140, y + 15, n, 't-tick', 'end'), f'<rect class="s1" x="150" y="{y + 3}" width="{w:.1f}" height="17" rx="3"/>', text(156 + w, y + 16, f'{m["wikitext_ppl"]:.2f}', 't-val')]
    y0 = 80 + len(models) * 26
    b.append(text(20, y0, '4-shot antonyms in a plain-text prompt (Chapter 4\'s task, higher is better)', 't-note'))
    for i, (n, m) in enumerate(models):
        y = y0 + 10 + i * 26
        w = 300 * m['antonyms_4shot']
        b += [text(140, y + 15, n, 't-tick', 'end'), f'<rect class="s3" x="150" y="{y + 3}" width="{w:.1f}" height="17" rx="3"/>', text(156 + w, y + 16, f'{m["antonyms_4shot"]:.0%}', 't-val')]
    yy = y0 + 20 + len(models) * 26
    return svg(780, yy + 6, 'Bars of wikitext-2 perplexity and 4-shot antonym accuracy for the base model, the fine-tuned models and Qwen Instruct.', b)


F['ch5_forgetting'] = forgetting()


# ---------------------------------------------------------------- 13. before / after answers
def before_after():
    if not (LORA and REF):
        return None
    q = "Give three tips for a good night's sleep."
    cols = [('base model (before)', REF['Qwen/Qwen2.5-0.5B']['samples'][q]), ('after LoRA SFT', LORA['samples'][q])]
    b = [text(20, 24, f'The same prompt before and after fine-tuning: "{q}"', 't-title')]
    hs = []
    for j, (name, s) in enumerate(cols):
        x = 20 + j * 385
        t = s['reply'].replace('\n', ' / ')
        lines = textwrap.wrap(t, 54)[:12]
        h = 50 + 17 * len(lines)
        hs.append(h)
        b += frame(x, 40, 370, h + 20, j + 1, name, 'box' if j == 0 else 'box-3')
        b += para(x + 16, 84, lines, 't-tick')
        b.append(text(x + 16, 84 + 17 * len(lines) + 10, 'ended its turn' if s['stopped'] else 'still going after 200 tokens (cut)', 't-muted'))
    return svg(790, 70 + max(hs) + 10, 'Two answers to the same prompt, from the base model and from the fine-tuned model.', b)


F['ch5_before_after'] = before_after()

# ---------------------------------------------------------------- 14. why plain LoRA could not say <|im_end|>
def tied_rows():
    if not SPEC:
        return None
    b = [text(20, 24, 'Why plain LoRA could not learn to stop (ch5_special_tokens.py)', 't-title')]
    b += block(20, 50, 230, 120, 'embedding = output layer', ['tied: one 151,936 x 896 matrix', 'LoRA freezes it', f'row norms: ordinary ~{SPEC["norm_mean"]:.2f}', f'<|im_end|> {SPEC["norm_imend"]:.3f}'], 'box-1')
    rows = [('" the"', 'trained', 's1', 0.9), ('" cat"', 'trained', 's1', 0.7), ('<|im_end|>', 'untrained', 's2', 0.35),
            ('id 124', 'untrained', 's2', 0.35), ('id 125', 'untrained', 's2', 0.35), ('...', '', 's2', 0.35), ('id 151847', 'untrained', 's2', 0.35)]
    x0 = 290
    b.append(text(x0, 54, 'rows of the matrix (same colour = same numbers)', 't-muted'))
    import random
    rnd = random.Random(4)
    pattern_u = [rnd.random() for _ in range(18)]
    for i, (name, kind, cls, op) in enumerate(rows):
        y = 66 + i * 22
        b.append(text(x0 + 82, y + 13, name, 't-tick', 'end'))
        pat = [rnd.random() for _ in range(18)] if kind == 'trained' else pattern_u
        if name == '...':
            continue
        for j, v in enumerate(pat[:14]):
            b.append(f'<rect class="{cls}" x="{x0 + 90 + j * 13}" y="{y + 2}" width="11" height="14" rx="2" style="fill-opacity:{0.2 + 0.7 * v:.2f}"/>')
    b += para(580, 74, [f'{SPEC["identical"]:,} rows are copies of', 'the <|im_end|> row, to within', 'bf16 rounding (cosine 1.000).', '',
                        'Whatever the hidden state,', 'they all get almost the same', 'score, so <|im_end|> cannot win.'], 't-tick')
    b += para(20, 236, ['The fix: make the two rows of <|im_start|> and <|im_end|> trainable (1,792 extra numbers). Then the model can give',
                        '<|im_end|> its own direction, and the loss on that token drops from 8.4 to 0.004 (Section 5.5).'], 't-muted')
    return svg(790, 262, 'The tied embedding matrix of Qwen2.5-0.5B: thousands of untrained rows, including <|im_end|>, hold the same numbers, so plain LoRA cannot make <|im_end|> more likely than the others.', b)


F['ch5_tied'] = tied_rows()

F = {k: v for k, v in F.items() if v}
json.dump(F, open('results/figs_ch5.json', 'w'))
print(f'{len(F)} figures:', ', '.join(F))
