"""Highlighted excerpts for Chapter 1 (from next word to assistant): GPT-3, InstructGPT, LIMA, URIAL, Qwen2.5, Llama 3,
OLMo 2, DeepSeek-R1 and Tulu 3.  Usage: python shots_ch1.py   (or ONLY=name1,name2 python shots_ch1.py)"""
from paper_shots import run

JOBS = [
    dict(name='ch1-gpt3-fig21', arxiv_id='2005.14165', page=6, figure=True, column='full',
         anchor='Figure 2.1: Zero-shot, one-shot and few-shot, contrasted with traditional fine-tuning',
         highlight=['Zero-shot, one-shot and few-shot, contrasted with traditional fine-tuning'], below=0),
    dict(name='ch1-instructgpt-fig2', arxiv_id='2203.02155', page=2, figure=True, column='full',
         anchor='Figure 2: A diagram illustrating the three steps of our method',
         highlight=['(1) supervised fine-tuning (SFT), (2) reward model (RM) training, and (3) reinforcement learning'], below=0),
    dict(name='ch1-instructgpt-cost', arxiv_id='2203.02155', page=16,
         anchor='The cost of collecting our data and the compute for training runs',
         highlight=['training our 175B SFT model requires 4.9 petaflops/s-days',
                    'training our 175B PPO-ptx model requires 60 petaflops/s-days',
                    'compared to 3,640 petaflops/s-days for GPT-3'],
         above=20, end='more cost-effective than training'),
    dict(name='ch1-lima-hypothesis', arxiv_id='2305.11206', page=1,
         anchor='We define the Superficial Alignment Hypothesis',
         highlight=['A model’s knowledge and capabilities are learnt almost entirely during pretraining',
                    'alignment teaches it which subdistribution of formats should be used when interacting with users'],
         above=16, end='a rather small set of examples'),
    dict(name='ch1-urial-fig2', arxiv_id='2312.01552', page=2, figure=True, column='full',
         anchor='Figure 2: Analyzing alignment with token distribution shift',
         highlight=['77.7% of tokens are also ranked top 1 by the base LLM', '92.2% are within the top 3',
                    'knowledge-intensive tokens are predominantly found in unshifted positions'], below=0),
    dict(name='ch1-urial-fig3', arxiv_id='2312.01552', page=3, figure=True, column='full',
         anchor='Figure 3: Token distribution shift on three pairs of base-vs-aligned LLMs',
         highlight=['Token distribution shift on three pairs of base-vs-aligned LLMs'], below=0),
    dict(name='ch1-qwen25-data', arxiv_id='2412.15115', page=1,
         anchor='Better in Data: The pre-training and post-training data have been improved significantly',
         highlight=['increased from 7 trillion tokens to 18 trillion tokens',
                    'The post-training data amounts to 1 million examples',
                    'supervised finetuning (SFT', 'direct preference optimization (DPO', 'group relative policy optimization (GRPO'],
         above=4, end='(GRPO, Shao et al., 2024).'),
    dict(name='ch1-llama3-fig7', arxiv_id='2407.21783', page=14, figure=True, column='full',
         anchor='Figure 7 Illustration of the overall post-training approach for Llama 3',
         highlight=['rejection sampling, supervised finetuning, and direct preference optimization'], below=0),
    dict(name='ch1-llama3-stages', arxiv_id='2407.21783', page=2,
         anchor='Language model pre-training. We start by converting a large',
         highlight=['we pre-train a model with 405B parameters on 15.6T tokens',
                    'it does not yet follow instructions or behave in the way we would expect an assistant to',
                    'supervised finetuning (SFT) on instruction tuning data and Direct Preference Optimization'],
         column='full', above=4, end='Section 4 for details.'),
    dict(name='ch1-olmo2-midtraining', arxiv_id='2501.00656', page=3,
         anchor='Mid-training Recipe. OLMo-0424',
         highlight=['splitting pretraining into two stages',
                    'mid-training stage being used to infuse new knowledge and patch deficiencies in capabilities'],
         above=4, end='(Section §4).'),
    dict(name='ch1-r1-reward', arxiv_id='2501.12948', page=2,
         anchor='For DeepSeek-R1-Zero, we employ rule-based rewards',
         highlight=['rule-based rewards', 'accuracy rewards and format rewards', 'enabling reliable rule-based verification'],
         above=40, end='rule-based verification'),
]

if __name__ == '__main__':
    run(JOBS)
