"""Highlighted excerpts of the BERT paper for Part 4 (Section 3.2, Section 4, Appendix A.3, A.5, B.1, Tables 1-4, Figure 4)."""
from paper_shots import run

JOBS = [
    # Section 3.2 Fine-tuning BERT (page 5, right column)
    dict(name='p4-finetune-swap', page=4, anchor='Fine-tuning is straightforward since the self',
         highlight=['swapping out the appropriate inputs and outputs', 'independently encode text pairs before applying bidirectional cross attention',
                    'effectively includes bidirectional cross attention between two sentences'],
         end='bidirectional cross attention between two sentences.', above=4),
    dict(name='p4-finetune-inputs', page=4, anchor='For each task, we simply plug in the task',
         highlight=['fine-tune all the parameters end-to-end', '(1) sentence pairs in paraphrasing', '(2) hypothesis-premise pairs in entailment',
                    '(3) question-passage pairs in question answering'],
         end='question-passage pairs in question answering, and', above=4),
    dict(name='p4-finetune-inputs2', page=4, anchor='a degenerate text',
         highlight=['a degenerate text', 'the token representations are fed into an output layer for token-level tasks',
                    'representation is fed into an output layer for classification'],
         end='such as entailment or sentiment analysis.', above=4),
    dict(name='p4-finetune-cost', page=4, anchor='Compared to pre-training, fine-tuning is rela',
         highlight=['in at most 1 hour on a single Cloud TPU, or a few hours on a GPU'], end='found in Appendix A.5.', above=4),
    dict(name='p4-footnote7', page=4, anchor='the BERT SQuAD model can be trained in',
         highlight=['around 30 minutes on a single Cloud TPU to achieve a Dev F1 score of 91.0%'], end='F1 score of 91.0%.', above=4),
    # Appendix A.5 and Figure 4
    dict(name='p4-a5', page=13, anchor='The illustration of fine-tuning BERT on different',
         highlight=['one additional output layer', '(a) and (b) are sequence-level tasks while (c) and (d) are token-level tasks'],
         end='non-consecutive token sequences.', above=36),
    dict(name='p4-figure4', page=14, anchor='Figure 4: Illustrations of Fine-tuning BERT on Different Tasks',
         highlight=['Figure 4: Illustrations of Fine-tuning BERT on Different Tasks'], figure=True, column='full', below=0),
    # Appendix A.3 fine-tuning procedure (page 13 right bottom, page 14 left top)
    dict(name='p4-a3', page=12, anchor='For fine-tuning, most model hyperparameters are',
         highlight=['with the exception of the batch size, learning rate, and number of training epochs', 'Batch size: 16, 32'],
         end='Batch size: 16, 32', above=22),
    dict(name='p4-a3b', page=13, anchor='We also observed that large data sets',
         highlight=['Learning rate (Adam): 5e-5, 3e-5, 2e-5', 'Number of epochs: 2, 3, 4', 'were far less sensitive to hyperparameter choice than small data sets'],
         end='performs best on the development set.', above=40),
    # Section 4 / 4.1 GLUE (page 5 bottom right)
    dict(name='p4-glue-intro', page=4, anchor='In this section, we present BERT fine-tuning re',
         highlight=['fine-tuning results on 11 NLP tasks', 'General Language Understanding Evaluation'],
         end='Appendix B.1.', above=22),
    dict(name='p4-glue-head', page=4, anchor='To fine-tune on GLUE, we represent the input',
         highlight=['corresponding to the first input token ([CLS]) as the aggregate representation',
                    'The only new parameters introduced during fine-tuning are classification layer weights',
                    'We compute a standard classification loss with C and W'],
         above=4, below=124),
    # Table 1 (page 6 top, full width)
    dict(name='p4-table1', page=5, anchor='Table 1: GLUE Test results, scored by the evaluation server',
         highlight=['Table 1: GLUE Test results'], figure=True, column='full', below=0),
    dict(name='p4-glue-setup', page=5, anchor='We use a batch size of 32 and fine-tune for 3',
         highlight=['batch size of 32 and fine-tune for 3 epochs', '(among 5e-5, 4e-5, 3e-5, and 2e-5) on the Dev set',
                    'fine-tuning was sometimes unstable on small datasets'],
         end='data shuffling and classifier layer', above=4),
    dict(name='p4-glue-results', page=5, anchor='Results are presented in Table 1',
         highlight=['obtaining 4.5% and 7.0% respective average accuracy improvement', 'BERTLARGE obtains a score of 80.5',
                    'which obtains 72.8 as of the date of writing'],
         end='as of the date of writing.', above=4),
    dict(name='p4-glue-size', page=5, anchor='We find that BERTLARGE significantly outper',
         highlight=['especially those with very little training data'], end='explored more thoroughly in Section 5.2.', above=4),
    # 4.2 SQuAD v1.1 (page 6 right)
    dict(name='p4-squad-intro', page=5, anchor='The Stanford Question Answering Dataset',
         highlight=['100k crowd-sourced question/answer pairs'], end='Given a question and a passage from', above=22),
    dict(name='p4-squad-se', page=5, anchor='Wikipedia containing the answer, the task is to',
         highlight=['predict the answer text span in the passage', 'We only introduce a start vector', 'The probability of word i being the start of the answer span',
                    'and the maximum scoring span where', 'The training objective is the sum of the log-likelihoods of the correct start and end positions'],
         end='with a learning rate of 5e-5 and a batch size of 32', above=4),
    dict(name='p4-squad-trivia', page=5, anchor='Table 2 shows top leaderboard entries as well',
         highlight=['by first fine-tuning on TriviaQA', '+1.5 F1 in ensembling and +1.3 F1 as a single system'],
         end='outperforms the top ensemble system in terms of F1 score.', above=4),
    dict(name='p4-squad-trivia2', page=6, anchor='tuning data, we only lose 0.1-0.4 F1',
         highlight=['we only lose 0.1-0.4 F1'], end='forming all existing systems by a wide', above=4),
    dict(name='p4-table2', page=6, anchor='SQuAD 1.1 results. The BERT ensemble',
         highlight=['BERTBASE (Single)', 'BERTLARGE (Ens.+TriviaQA)'], figure=True, below=0, fig_top=196),
    # 4.3 SQuAD v2.0 (page 7)
    dict(name='p4-squad2', page=6, anchor='The SQuAD 2.0 task extends the SQuAD 1.1',
         highlight=['no short answer exists in the provided paragraph', 'as having an answer span with start and end at the [CLS] token',
                    'compare the score of the no-answer span'],
         end='the score of the best non-null span', above=22),
    dict(name='p4-squad2b', page=6, anchor='We predict a non-null',
         highlight=['We predict a non-null', 'is selected on the dev set to maximize F1', 'We observe a +5.1 F1 improvement over the previous best system'],
         end='over the previous best system.', above=16),
    dict(name='p4-table3', page=6, anchor='SQuAD 2.0 results. We exclude entries that',
         highlight=['BERTLARGE (Single)'], hl_nth={'BERTLARGE (Single)': 1}, figure=True, below=0, fig_top=150),
    # 4.4 SWAG
    dict(name='p4-swag', page=6, anchor='The Situations With Adversarial Generations',
         highlight=['choose the most plausible continuation among four choices', 'we construct four input sequences',
                    'a vector whose dot product with the [CLS] token representation C denotes a score for each choice',
                    'outperforms the authors’ baseline ESIM+ELMo system by +27.1% and OpenAI GPT by 8.3%'],
         end='OpenAI GPT by 8.3%.', above=22),
    dict(name='p4-table4', page=6, anchor='Table 4: SWAG Dev and Test accuracies',
         highlight=['Table 4: SWAG Dev and Test accuracies'], figure=True, below=0, fig_top=126),
    # Appendix B.1 GLUE tasks (pages 14 and 15)
    dict(name='p4-b1a', page=13, anchor='Our GLUE results in Table1 are obtained from',
         highlight=['MNLI', 'QQP', 'QNLI'], hl_nth={'MNLI': 0}, end='which do not contain the answer.', above=36),
    dict(name='p4-b1b', page=14, anchor='The Stanford Sentiment Treebank is a',
         highlight=['SST-2', 'CoLA', 'STS-B', 'MRPC'], end='from online news sources, with human annotations', above=4),
    dict(name='p4-b1c', page=14, anchor='for whether the sentences in the pair are semanti',
         highlight=['RTE', 'WNLI', 'performed worse than the 65.1 baseline accuracy of predicting the majority class',
                    'We therefore exclude this set to be fair to OpenAI GPT'],
         end='We therefore exclude this set to be fair to OpenAI GPT', above=4),
    # new in v2: more of Section 4's own lines and footnotes
    dict(name='p4-gpt-arch', page=5, anchor='Note that BERTBASE and OpenAI GPT are nearly',
         highlight=['nearly identical in terms of model architecture apart from the at', 'BERT obtains a 4.6% absolute accuracy improvement'],
         end='absolute accuracy improvement.', above=4),
    dict(name='p4-footnote9', page=5, anchor='GLUE data set distribution does not include the Test',
         highlight=['we only made a single GLUE evaluation server submission'], above=4, below=22),
    dict(name='p4-footnote11', page=5, anchor='is described in Yu et al. (2018), but the',
         highlight=['the system has improved substantially after publication'], end='substantially after publication.', above=4),
    dict(name='p4-footnote12', page=6, anchor='TriviaQA data we used consists of paragraphs',
         highlight=['first 400 tokens in documents', 'at least one of the provided possible answers'], end='possible answers.', above=4),
    # the papers Part 4 leans on: SQuAD, SQuAD 2.0, SWAG, GLUE, BiDAF, decomposable attention
    dict(name='p4-x-squad-fig1', arxiv_id='1606.05250', page=0, anchor='Figure 1: Question-answer pairs for a sample passage',
         highlight=['Each of the answers is a segment of text from'], figure=True, fig_top=236, below=30),
    dict(name='p4-x-squad2-fig1', arxiv_id='1806.03822', page=0, anchor='Two unanswerable questions written by',
         highlight=['Two unanswerable questions written by'], figure=True, fig_top=150, below=0),
    dict(name='p4-x-swag-table1', arxiv_id='1808.05326', page=0, anchor='Table 1: Examples from Swag',
         highlight=['the correct answer is bolded'], figure=True, fig_top=192, below=0),
    dict(name='p4-x-glue-table1', arxiv_id='1804.07461', page=1, anchor='Table 1: Task descriptions and statistics',
         highlight=['Matthews corr.', 'matched acc./mismatched acc.'], figure=True, column='full', fig_top=180, below=0),
    dict(name='p4-x-bidaf-fig1', arxiv_id='1611.01603', page=1, anchor='Figure 1: BiDirectional Attention Flow Model',
         highlight=['Attention Flow Layer'], figure=True, column='full', below=0),
    dict(name='p4-x-decomp-fig1', arxiv_id='1606.01933', page=1, anchor='Figure 1: Pictoral overview of the approach',
         highlight=['showing the Attend', 'Compare (center)', 'Aggregate (right)'], figure=True, fig_top=95, below=16),
]

if __name__ == '__main__':
    run(JOBS)
