"""Highlighted excerpts of the BERT paper for Part 5 (Section 5 ablations, Appendix A.4, C.1, C.2)."""
from paper_shots import run

JOBS = [
    dict(name='p5-intro', page=6, anchor='In this section, we perform ablation experiments',
         highlight=['ablation experiments over a number of facets of BERT'], end='understand their relative importance.', above=24),
    dict(name='p5-setup', page=7, anchor='We demonstrate the importance of the deep bidi',
         highlight=['using exactly the same pre-training data, fine-tuning scheme, and hyperparameters', 'No NSP:', 'LTR & No NSP:',
                    'This is directly comparable to OpenAI GPT'], end='and our fine-tuning scheme.', above=24),
    dict(name='p5-table5', page=7, anchor='Table 5: Ablation over the pre-training tasks using the',
         highlight=['Table 5: Ablation over the pre-training tasks'], figure=True, below=0, fig_top=92),
    dict(name='p5-nsp-ltr', page=7, anchor='We first examine the impact brought by the NSP',
         highlight=['removing NSP hurts performance significantly on QNLI, MNLI, and SQuAD 1.1',
                    'The LTR model performs worse than the MLM model on all tasks, with large drops on MRPC and SQuAD'],
         end='with large drops on MRPC and SQuAD.', above=4),
    dict(name='p5-bilstm', page=7, anchor='For SQuAD it is intuitively clear that a LTR',
         highlight=['since the token-level hidden states have no right-side context', 'we added a randomly initialized BiLSTM on top'],
         above=4, below=90),
    dict(name='p5-bilstm2', page=7, anchor='results are still far worse than those of the pre',
         highlight=['The BiLSTM hurts performance on the GLUE tasks'], end='performance on the GLUE tasks.', above=4),
    dict(name='p5-elmo-args', page=7, anchor='We recognize that it would also be possible to',
         highlight=['twice as expensive as a single bidirectional model', 'the RTL model would not be able to condition the answer on the question',
                    'strictly less powerful than a deep bidirectional model'], end='both left and right context at every layer.', above=4),
    dict(name='p5-size-intro', page=7, anchor='In this section, we explore the effect of model size',
         highlight=['we report the average Dev Set accuracy from 5 random restarts of fine-tuning', 'larger models lead to a strict accuracy improvement across all four datasets',
                    'only has 3,600 labeled training examples'], end='already quite large relative to the existing literature.', above=4),
    dict(name='p5-size-prior', page=7, anchor='For example, the largest Transformer explored in',
         highlight=['(L=6, H=1024, A=16) with 100M parameters for the encoder', '(L=64, H=512, A=2) with 235M parameters',
                    'BERTBASE contains 110M parameters and BERTLARGE contains 340M parameters'], end='contains 340M parameters.', above=4),
    dict(name='p5-size-claim', page=7, anchor='It has long been known that increasing the',
         highlight=['scaling to extreme model sizes also leads to large improvements on very small scale tasks, provided that the model has been sufficiently pre-trained'],
         end='Peters et al. (2018b) presented', above=4),
    dict(name='p5-size-claim2', page=8, anchor='mixed results on the downstream task impact of',
         highlight=['the task-specific models can benefit from the larger, more expressive pre-trained representations even when downstream task data is very small'],
         end='downstream task data is very small.', above=4),
    dict(name='p5-table6', page=8, anchor='Table 6: Ablation over BERT model size',
         highlight=['Table 6: Ablation over BERT model size'], figure=True, below=0, fig_top=116),
    dict(name='p5-feature-why', page=8, anchor='All of the BERT results presented so far have used',
         highlight=['the feature-based approach, where fixed features are extracted from the pretrained model, has certain advantages',
                    'not all tasks can be easily represented by a Transformer encoder architecture',
                    'major computational benefits to pre-compute an expensive representation of the training data once'],
         end='cheaper models on top of this representation.', above=4),
    dict(name='p5-feature-setup', page=8, anchor='In this section, we compare the two approaches',
         highlight=['case-preserving WordPiece model', 'maximal document context', 'do not use a CRF'],
         end='formulate this as a tagging task but do not use a CRF', above=4),
    dict(name='p5-feature-setup-b', page=8, anchor='layer in the output. We use the representation of',
         highlight=['the first sub-token'], end='classifier over the NER label set.', above=4),
    dict(name='p5-feature-setup2', page=8, anchor='To ablate the fine-tuning approach, we apply the',
         highlight=['without fine-tuning any parameters of BERT', 'randomly initialized two-layer 768-dimensional BiLSTM'],
         end='before the classification layer.', above=4),
    dict(name='p5-table7', page=8, anchor='Table 7: CoNLL-2003 Named Entity Recognition',
         highlight=['Concat Last Four Hidden'], figure=True, below=0, fig_top=175),
    dict(name='p5-feature-result', page=8, anchor='Results are presented in Table 7',
         highlight=['concatenates the token representations from the top four hidden layers', 'only 0.3 F1 behind fine-tuning the entire model'],
         end='tuning and feature-based approaches.', above=4),
    dict(name='p5-a4', page=13, anchor='The most comparable existing pre-training',
         highlight=['GPT is trained on the BooksCorpus (800M words)', 'GPT uses a sentence separator', 'which are only introduced at fine-tuning time',
                    'GPT was trained for 1M steps with a batch size of 32,000 words', 'GPT used the same learning rate of 5e-5'],
         end='performs the best on the development set.', above=4),
    dict(name='p5-a4-end', page=13, anchor='To isolate the effect of these differences, we per',
         highlight=['the majority of the improvements are in fact coming from the two pre-training tasks and the bidirectionality they enable'],
         end='bidirectionality they enable.', above=4),
    dict(name='p5-c1', page=15, anchor='Figure 5 presents MNLI Dev accuracy after fine',
         highlight=['almost 1.0% additional accuracy on MNLI when trained on 1M steps compared to 500k steps',
                    'The MLM model does converge slightly slower than the LTR model',
                    'the MLM model begins to outperform the LTR model almost immediately'], end='almost immediately.', above=4),
    dict(name='p5-figure5', page=15, anchor='Figure 5: Ablation over number of training steps',
         highlight=['Figure 5: Ablation over number of training steps'], figure=True, below=0),
    dict(name='p5-c2', page=15, anchor='In Section 3.1, we mention that BERT uses a',
         highlight=['mixed strategy for masking the target tokens'], end='strategies.', above=4),
    dict(name='p5-c2-why', page=15, anchor='Note that the purpose of the masking strategies',
         highlight=['reduce the mismatch between pre-training and fine-tuning', 'the mismatch will be amplified for the feature-based approach'],
         end='adjust the representations.', above=4),
    dict(name='p5-table8', page=15, anchor='Table 8: Ablation over different masking strategies',
         highlight=['Table 8: Ablation over different masking strategies'], figure=True, below=0, fig_top=122),
    dict(name='p5-c2-legend', page=15, anchor='The results are presented in Table 8',
         highlight=['MASK means that we replace the target token with the [MASK] symbol', 'SAME means that we keep the target token as is',
                    'RND means that we replace the target token with another random token', 'BERT uses 80%, 10%, 10%',
                    'we concatenate the last 4 layers of BERT as the features'], end='best approach in Section 5.3.', above=4),
    dict(name='p5-c2-result', page=15, anchor='From the table it can be seen that fine-tuning is',
         highlight=['fine-tuning is surprisingly robust to different masking strategies',
                    'using only the MASK strategy was problematic when applying the feature-based approach to NER',
                    'using only the RND strategy performs much worse than our strategy as well'], end='than our strategy as well.', above=4),
    # ---- added in the second pass: the A.4 opening, and the other papers Section 5 talks to
    dict(name='p5-a4-open', page=13, anchor='Comparison of BERT, ELMo',
         highlight=['BERT and OpenAI GPT are fine-tuning approaches, while ELMo is a feature-based approach',
                    'intentionally made to make it as close to GPT as possible', 'account for the majority of the empirical improvements'],
         end='between how BERT and GPT were trained:', above=6),
    dict(name='p5-vaswani-table3', arxiv_id='1706.03762', page=8, anchor='Table 3: Variations on the Transformer architecture',
         highlight=['big 6 1024 4096 16', '213'], column='full', end='big 6 1024 4096 16', above=4),
    dict(name='p5-alrfou-table1', arxiv_id='1808.04444', page=3, anchor='Table 1: Comparison of various models on text8',
         highlight=['T64 (ours) 235 219 1.13', 'Parameters'], figure=True, below=0, fig_top=104, column='full'),
    dict(name='p5-alrfou-abstract', arxiv_id='1808.04444', page=0, anchor='In this paper, we show that a deep',
         highlight=['a deep (64-layer) transformer model'], end='by a large margin', above=4, below=30),
    dict(name='p5-elmo-eq1', arxiv_id='1802.05365', page=2, anchor='as in TagLM (Peters et al., 2017) and CoVe',
         highlight=['task specific weighting of all biLM layers', 'softmax-normalized weights'], end='allows the task model to scale the entire ELMo vector', above=4),
    dict(name='p5-conll-format', arxiv_id='cs/0306050', page=1, anchor='All data files contain one word per line with empty',
         highlight=['the I-XXX tag is used for words inside a named entity of type XXX', 'will be tagged B-XXX', 'the IOB scheme originally put forward by Ramshaw and Marcus (1995)'], end='Ramshaw and Marcus (1995)', above=24),
]

if __name__ == '__main__':
    run(JOBS)
    import os
    from PIL import Image
    from paper_shots import OUT
    f = os.path.join(OUT, 'p5-alrfou-table1.png')        # the table is wider than its column: keep the table, drop the next column's text
    if (not os.environ.get('ONLY') or 'p5-alrfou-table1' in os.environ['ONLY']) and os.path.exists(f):
        im = Image.open(f)
        if im.width > 1000:
            im.crop((0, 0, 700, im.height)).save(f)
